name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line   script
        run: |
          dotnet restore src/ProjectTemplate.sln
          dotnet test src/ProjectTemplate.sln
          dotnet build src/ProjectTemplate.sln
          
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.6
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          
      - name: Create nuget package
        run: nuget pack JacobsApps.CSharp.ProjectTemplate.CleanArchitecture.Api.nuspec -NoDefaultExcludes

      - name: Push nuget package
      if: startsWith(github.ref, 'refs/tags/v')
      run: nuget push JacobsApps.CleanArchitectureProjectTemplate.CSharp.*.nupkg -Source https://api.nuget.org/v3/index.json
